# Set TEST_BUILDS=1 to run library_builders tests

language: generic

cache:
  directories:
   - $HOME/.ccache

env:
  global:
    - PLAT=x86_64

matrix:
  include:
    - os: osx
      osx_image: xcode11
      env:
        - PYTHON_VERSION=3.7
        - TEST_BUILDS=1

script:
  - export ENV_VARS_PATH="tests/env_vars.sh"
  - source tests/test_multibuild.sh
