# Set TEST_BUILDS=1 to run library_builders tests

language: generic

cache:
  directories:
   - $HOME/.ccache

matrix:
  include:
    - os: osx
      osx_image: xcode11
      env:
        - PYTHON_VERSION=3.7
        - TEST_BUILDS=1
    - os: osx
      osx_image: xcode11
      env:
        - PYTHON_VERSION=3.7
        - MB_PYTHON_OSX_VER=10.9
        - TEST_BUILDS=1
    - os: osx
      osx_image: xcode10.1
      env:
        - PYTHON_VERSION=3.7
        - TEST_BUILDS=1
    - os: osx
      osx_image: xcode10.1
      env:
        - PYTHON_VERSION=3.5

script:
  - export ENV_VARS_PATH="tests/env_vars.sh"
  - source tests/test_multibuild.sh
