# Set TEST_BUILDS=1 to run library_builders tests

language: generic

cache:
  directories:
   - $HOME/.ccache

env:
    global:
        # Always set Python version
        - MB_PYTHON_VERSION=3.7

matrix:
  include:
    # OSX builds
    - os: osx
      env:
        - MB_PYTHON_VERSION=2.7
        - MB_PYTHON_OSX_VER=10.6
        - TEST_BUILDS=1
        - OPENSSL_ROOT=openssl-1.0.2u
        - OPENSSL_HASH=ecd0c6ffb493dd06707d38b14bb4d8c2288bb7033735606569d8f90f89669d16

script:
  - export ENV_VARS_PATH="tests/env_vars.sh"
  - source tests/test_multibuild.sh
